### PR TITLE
Adding the spotify model with accuracy of 83% on validation set

### PR DESCRIPTION
**Pull request by nikhiltitus**
I have added a model which reaches 83% accuracy on validation set. By default the LSTM model will be chosen. There is a command line parameter called model_choice which switches to the second model which uses global temporal pooling layers more info here: http://benanne.github.io/2014/08/05/spotify-cnns.html

### CODE REVIEW

**Comment by nikhiltitus** [comment]
screen shot 2018-01-09 at 6 06 40 pm

Attaching the screen shot for improved accuracy.

**Comment by koz4k** [comment]
That's a great improvement, but I don't think it will work with our visualization. For this, we need a model outputing a probability distribution over genres in each timestep and the one you implemented outputs a single distribution for the whole piece.

**Comment by nikhiltitus** [comment]
Yep, I agree.. I have set your model as default for training. Do you still want to keep the model that I am suggesting for those who are interested. Can put a disclaimer in readme too. My model can only be activated using:
```
python train_model.py -c 2 
```

**Comment by nikhiltitus** [comment]
I have added a warning message in the README.

**Comment by koz4k** [comment]
Thank you, but we'd rather keep the model compatible with the visualization, as we see the model as just a part of a bigger application. You are very welcome to publish your own fork with this new model included.

**Comment by nikhiltitus** [comment]
Sure. Thanks. I am closing this merge request.

**Pull request closed without merging**
